name: Autocommit Documentation Changes

on:
  push:
    branches:
      - main # Target default branch

permissions:
  contents: write # Required to push commit

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Generate Documentation
        run: bun run docs

      - name: Commit and Push Documentation Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Auto-generate documentation [skip ci]"
          commit_options: '--no-verify'
          skip_dirty_check: false # Only commit if changes exist
